### ISSUE TITLE
How to backup existing subvolumes into another subvolume

### ISSUE THREAD

**Issue by nazar-pc** [ruediste/btrbck#5]
I have similar question to #1, but do not understand why do I need to move something somewhere, and because of long explanation decided to open new issue.

I have btrfs partition with subvolumes:
- `/root` (mounted as `/`)
- `/home` (mounted as `/home`)
- `/web` (mounted as `/web`)

Now I want to create subvolume `/backup`, mount it to `/backup` and store read-only snapshots of above subvolumes inside, ideally like this:
- `/backup/root/{backup_name_with_date}`
- `/backup/home/{backup_name_with_date}`
- `/backup/web/{backup_name_with_date}`

This will allow me to see all backups just by opening `/backup`.

But from readme it is not clear how to do so. Looks like after stream creation I can only put files inside it (also I do not want to see any additional directories inside existing subvolumes, I want to remain them unchanged, while I agree to have something inside `/backup` and `/backup/*`).

Actually, readme is hard to read because of focusing on snapshots transfering and involving 2 machines, while I'm interested in such very simple case with backups rotating and looking for solution in order to avoid writing my own.

It would be great to create few pages here in wiki with few use cases, because, for instance, I have no idea what is `0` in `btrbck restore myStream 0` and what it actually does, it might be obvious for you, but now for others.

**Comment by jutoft** [comment]
# First prepare backup dir
Go to /backup
* `cd /backup`
* `btrbck create -a`
* `btrbck create root`
* `btrbck create home`
* `btrbck create web`
# Then remove the created volumes
* `btrfs subvolume delete /backup/root`
* `btrfs subvolume delete /backup/home`
* `btrfs subvolume delete /backup/web`
# Create symbolic links in their place
* `ln -s / root`
* `ln -s /home home`
* `ln -s /web web`
# This doesn't allow easy access but that can be done by making another dir with snapshots
* `mkdir /backup/snapshots/`
* `ln -s /backup/.backup/root/snapshots/ /backup/snapshots/root`
* `ln -s /backup/.backup/home/snapshots/ /backup/snapshots/home`
* `ln -s /backup/.backup/web/snapshots/ /backup/snapshots/web`
